# -*- coding: utf-8 -*-
"""Copy of Drowsiness_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11i1rZpu1MIhFJTjPrSw_d7m8cMO5Q9Q4
"""

# CELL 1 - ENVIRONMENT CHECK

import sys
import torch

print("Python version:")
print(sys.version)

print("\nPyTorch version:")
print(torch.__version__)

print("\nGPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Using CPU")

# CELL 2 - INSTALL LIBRARIES

!pip install -q torch torchvision pillow matplotlib scikit-learn opencv-python mediapipe

# CELL 3 - IMPORT LIBRARIES

import os
import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

from torchvision import models, transforms
from torchvision.datasets import ImageFolder

from torch.utils.data import Dataset, DataLoader

from PIL import Image

print("All libraries imported successfully!")

# CELL 4 - DEVICE & RANDOM SEED

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", DEVICE)

# CELL 5 - UPLOAD DATASET

from google.colab import files

print("Upload your drowsiness dataset ZIP file.")

uploaded = files.upload()

print("\nUploaded:")
for filename in uploaded.keys():
    print("✅", filename)

# CELL 6 - EXTRACT DATASET

import zipfile
from pathlib import Path

ZIP_FILE = next(iter(uploaded.keys()))

EXTRACT_DIR = Path("/content/drowsiness_dataset")

# Create extraction folder
EXTRACT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

with zipfile.ZipFile(ZIP_FILE, "r") as zip_ref:

    zip_ref.extractall(EXTRACT_DIR)

print("✅ Dataset extracted!")
print("Location:", EXTRACT_DIR)

# CELL 7 - FIND DATASET SPLITS

TRAIN_DIR = None
VAL_DIR = None
TEST_DIR = None

for folder in EXTRACT_DIR.rglob("*"):

    if not folder.is_dir():
        continue

    name = folder.name.lower()

    if name in ["train", "training"] and TRAIN_DIR is None:
        TRAIN_DIR = folder

    elif name in ["validation", "valid", "val"] and VAL_DIR is None:
        VAL_DIR = folder

    elif name in ["test", "testing"] and TEST_DIR is None:
        TEST_DIR = folder


print("========================================")
print("       DATASET LOCATIONS")
print("========================================")

print("TRAIN      :", TRAIN_DIR)
print("VALIDATION :", VAL_DIR)
print("TEST       :", TEST_DIR)


if TRAIN_DIR is None:
    raise FileNotFoundError(
        "Train folder not found."
    )

if VAL_DIR is None:
    raise FileNotFoundError(
        "Validation folder not found."
    )

if TEST_DIR is None:
    raise FileNotFoundError(
        "Test folder not found."
    )

print("\n✅ All three dataset splits found!")

# CELL 8 - CHECK DATASET CLASSES

classes = sorted([
    folder.name
    for folder in TRAIN_DIR.iterdir()
    if folder.is_dir()
])

print("Classes found:")
print()

for i, class_name in enumerate(classes):
    print(i, "->", class_name)

print("\nTotal classes:", len(classes))

# CELL 9 - COUNT DATASET IMAGES

IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".webp"
}

def count_images(folder):

    counts = {}

    for class_folder in sorted(folder.iterdir()):

        if not class_folder.is_dir():
            continue

        count = sum(
            1
            for file in class_folder.rglob("*")
            if file.is_file()
            and file.suffix.lower() in IMAGE_EXTENSIONS
        )

        counts[class_folder.name] = count

    return counts


train_counts = count_images(TRAIN_DIR)
val_counts = count_images(VAL_DIR)
test_counts = count_images(TEST_DIR)

print("TRAINING IMAGES")

for class_name, count in train_counts.items():
    print(f"{class_name:15} : {count}")


print("\n VALIDATION IMAGES")

for class_name, count in val_counts.items():
    print(f"{class_name:15} : {count}")


print("\n TEST IMAGES")

for class_name, count in test_counts.items():
    print(f"{class_name:15} : {count}")


print("\n TOTALS")

print("Train      :", sum(train_counts.values()))
print("Validation :", sum(val_counts.values()))
print("Test       :", sum(test_counts.values()))
print(
    "Total      :",
    sum(train_counts.values())
    + sum(val_counts.values())
    + sum(test_counts.values())
)

# CELL 10 - CHECK FOR CORRUPTED IMAGES

from PIL import Image

def check_corrupted_images(folder):

    corrupted = []

    for file in folder.rglob("*"):

        if not file.is_file():
            continue

        if file.suffix.lower() not in IMAGE_EXTENSIONS:
            continue

        try:
            with Image.open(file) as img:
                img.verify()

        except Exception:
            corrupted.append(file)

    return corrupted


print("Checking Train images...")
train_corrupted = check_corrupted_images(TRAIN_DIR)

print("Checking Validation images...")
val_corrupted = check_corrupted_images(VAL_DIR)

print("Checking Test images...")
test_corrupted = check_corrupted_images(TEST_DIR)


all_corrupted = (
    train_corrupted
    + val_corrupted
    + test_corrupted
)

print("CORRUPTED IMAGE CHECK")

print("Train corrupted      :", len(train_corrupted))
print("Validation corrupted :", len(val_corrupted))
print("Test corrupted       :", len(test_corrupted))
print("Total corrupted      :", len(all_corrupted))


if len(all_corrupted) == 0:

    print("\n✅ No corrupted images found!")

else:

    print("\n⚠️ Corrupted images found.")
    print("First few corrupted files:")

    for file in all_corrupted[:10]:
        print(file)

# CELL 11 - VISUALIZE DATASET SAMPLES

import matplotlib.pyplot as plt
from PIL import Image
import random

# Number of images from each class
SAMPLES_PER_CLASS = 2

plt.figure(figsize=(12, 8))

plot_number = 1

for class_name in classes:

    class_folder = TRAIN_DIR / class_name

    image_files = [
        file
        for file in class_folder.rglob("*")
        if file.is_file()
        and file.suffix.lower() in IMAGE_EXTENSIONS
    ]

    selected_images = random.sample(
        image_files,
        SAMPLES_PER_CLASS
    )

    for image_file in selected_images:

        image = Image.open(image_file).convert("RGB")

        plt.subplot(
            len(classes),
            SAMPLES_PER_CLASS,
            plot_number
        )

        plt.imshow(image)

        plt.title(class_name)

        plt.axis("off")

        plot_number += 1


plt.tight_layout()

plt.show()

# CELL 12 - IMAGE PREPROCESSING

from torchvision import transforms

# Image size required by ResNet18
IMAGE_SIZE = 224

# Training transformation
# These small changes help the model handle
# different face/eye/mouth positions and lighting.
train_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),

    transforms.RandomHorizontalFlip(p=0.5),

    transforms.RandomRotation(degrees=8),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# Validation and testing
# No random changes here because we want
# consistent evaluation.
val_test_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


print("✅ Image preprocessing ready!")
print("Image size:", IMAGE_SIZE, "x", IMAGE_SIZE)

# CELL 13 - LOAD TRAIN / VALIDATION / TEST DATASETS

train_full = ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_full = ImageFolder(
    VAL_DIR,
    transform=val_test_transform
)

test_full = ImageFolder(
    TEST_DIR,
    transform=val_test_transform
)

print("✅ Datasets loaded successfully!")

print("\nDataset classes:")
print(train_full.classes)

print("\nNumber of images:")
print("Train      :", len(train_full))
print("Validation :", len(val_full))
print("Test       :", len(test_full))

# CELL 14 - BINARY DATASET CLASS

class BinaryDrowsinessDataset(Dataset):

    def __init__(
        self,
        image_folder_dataset,
        selected_classes
    ):
        self.dataset = image_folder_dataset

        self.selected_classes = selected_classes

        # Convert class names to new labels
        self.class_to_idx = {
            class_name: index
            for index, class_name
            in enumerate(selected_classes)
        }

        self.selected_indices = []

        # Select only required classes
        for index, (_, label) in enumerate(
            self.dataset.samples
        ):

            original_class = (
                self.dataset.classes[label]
            )

            if original_class in selected_classes:

                self.selected_indices.append(index)

    def __len__(self):

        return len(self.selected_indices)

    def __getitem__(self, index):

        original_index = (
            self.selected_indices[index]
        )

        image, original_label = (
            self.dataset[original_index]
        )

        original_class = (
            self.dataset.classes[original_label]
        )

        new_label = self.class_to_idx[
            original_class
        ]

        return image, new_label

print("✅ Binary dataset class created!")

# CELL 15 - EYE DATASETS

eye_classes = [
    "Closed_Eyes",
    "Open_Eyes"
]

eye_train = BinaryDrowsinessDataset(
    train_full,
    eye_classes
)

eye_val = BinaryDrowsinessDataset(
    val_full,
    eye_classes
)

eye_test = BinaryDrowsinessDataset(
    test_full,
    eye_classes
)

print("EYE MODEL DATASET")

print("Classes:", eye_classes)

print("Train      :", len(eye_train))
print("Validation :", len(eye_val))
print("Test       :", len(eye_test))

# CELL 16 - YAWN DATASETS

yawn_classes = [
    "No_yawn",
    "Yawn"
]

yawn_train = BinaryDrowsinessDataset(
    train_full,
    yawn_classes
)

yawn_val = BinaryDrowsinessDataset(
    val_full,
    yawn_classes
)

yawn_test = BinaryDrowsinessDataset(
    test_full,
    yawn_classes
)

print("YAWN MODEL DATASET")

print("Classes:", yawn_classes)

print("Train      :", len(yawn_train))
print("Validation :", len(yawn_val))
print("Test       :", len(yawn_test))

# CELL 17 - CREATE DATALOADERS

BATCH_SIZE = 32

eye_train_loader = DataLoader(
    eye_train,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2
)

eye_val_loader = DataLoader(
    eye_val,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

eye_test_loader = DataLoader(
    eye_test,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

yawn_train_loader = DataLoader(
    yawn_train,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2
)

yawn_val_loader = DataLoader(
    yawn_val,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

yawn_test_loader = DataLoader(
    yawn_test,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2
)

print("✅ DataLoaders created!")
print("Batch size:", BATCH_SIZE)

# CELL 18 - CHECK ONE BATCH

images, labels = next(iter(eye_train_loader))

print("Images shape :", images.shape)
print("Labels shape :", labels.shape)

print("\nFirst 10 labels:")
print(labels[:10])

print("\nLabel meanings:")
print("0 =", eye_classes[0])
print("1 =", eye_classes[1])

# CELL 19 - CREATE RESNET18 MODELS

from torchvision import models
import torch.nn as nn

def create_drowsiness_model():

    model = models.resnet18(
        weights=models.ResNet18_Weights.DEFAULT
    )

    # Replace the final layer
    # 2 outputs = 2 classes
    model.fc = nn.Linear(
        model.fc.in_features,
        2
    )

    return model.to(DEVICE)

# Create Eye Model
eye_model = create_drowsiness_model()

# Create Yawn Model
yawn_model = create_drowsiness_model()

print("✅ Eye model created!")
print("✅ Yawn model created!")

print("\nDevice:", DEVICE)

# CELL 20 - TRAINING CONFIGURATION

import torch.optim as optim

EPOCHS = 5
LEARNING_RATE = 0.0001

criterion = nn.CrossEntropyLoss()

eye_optimizer = optim.Adam(
    eye_model.parameters(),
    lr=LEARNING_RATE
)

yawn_optimizer = optim.Adam(
    yawn_model.parameters(),
    lr=LEARNING_RATE
)

print("TRAINING CONFIGURATION")

print("Epochs        :", EPOCHS)
print("Learning rate :", LEARNING_RATE)
print("Loss function :", "CrossEntropyLoss")
print("Optimizer     :", "Adam")

# CELL 21 - TRAINING AND VALIDATION FUNCTION

def train_one_epoch(model, loader, optimizer, criterion):

    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        # Clear previous gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(images)

        # Calculate loss
        loss = criterion(outputs, labels)

        # Backpropagation
        loss.backward()

        # Update model
        optimizer.step()

        # Statistics
        running_loss += loss.item() * images.size(0)

        predictions = torch.argmax(
            outputs,
            dim=1
        )

        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy

def validate_model(model, loader, criterion):

    model.eval()

    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            outputs = model(images)

            loss = criterion(
                outputs,
                labels
            )

            running_loss += (
                loss.item() * images.size(0)
            )

            predictions = torch.argmax(
                outputs,
                dim=1
            )

            correct += (
                predictions == labels
            ).sum().item()

            total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_accuracy = correct / total

    return epoch_loss, epoch_accuracy

print("Training and validation functions ready!")

# CELL 22 - TRAIN EYE MODEL

import copy
import time

EYE_EPOCHS = 5

best_eye_val_accuracy = 0.0

eye_history = {
    "train_loss": [],
    "train_accuracy": [],
    "val_loss": [],
    "val_accuracy": []
}

print("TRAINING EYE MODEL")

for epoch in range(EYE_EPOCHS):

    start_time = time.time()

    # TRAIN

    train_loss, train_accuracy = train_one_epoch(
        eye_model,
        eye_train_loader,
        eye_optimizer,
        criterion
    )

    # VALIDATE

    val_loss, val_accuracy = validate_model(
        eye_model,
        eye_val_loader,
        criterion
    )

    # Save history

    eye_history["train_loss"].append(train_loss)
    eye_history["train_accuracy"].append(train_accuracy)

    eye_history["val_loss"].append(val_loss)
    eye_history["val_accuracy"].append(val_accuracy)

    elapsed = time.time() - start_time

    print(
        f"Epoch [{epoch + 1}/{EYE_EPOCHS}] "
        f"| Train Loss: {train_loss:.4f} "
        f"| Train Acc: {train_accuracy * 100:.2f}% "
        f"| Val Loss: {val_loss:.4f} "
        f"| Val Acc: {val_accuracy * 100:.2f}% "
        f"| Time: {elapsed:.1f}s"
    )

    # SAVE BEST MODEL

    if val_accuracy > best_eye_val_accuracy:

        best_eye_val_accuracy = val_accuracy

        torch.save(
            eye_model.state_dict(),
            "/content/eye_model.pth"
        )

        print("Best Eye Model saved!")

print("Eye Model Training Complete!")
print("Best Validation Accuracy:",
      f"{best_eye_val_accuracy * 100:.2f}%")

# cell 23

import copy
import time

EYE_EPOCHS = 5

best_eye_val_accuracy = 0.0

eye_history = {
    "train_loss": [],
    "train_accuracy": [],
    "val_loss": [],
    "val_accuracy": []
}

for epoch in range(EYE_EPOCHS):

    start_time = time.time()

    # Training
    train_loss, train_accuracy = train_one_epoch(
        eye_model,
        eye_train_loader,
        eye_optimizer,
        criterion
    )

    # Validation
    val_loss, val_accuracy = validate_model(
        eye_model,
        eye_val_loader,
        criterion
    )

    # Save history
    eye_history["train_loss"].append(train_loss)
    eye_history["train_accuracy"].append(train_accuracy)
    eye_history["val_loss"].append(val_loss)
    eye_history["val_accuracy"].append(val_accuracy)

    elapsed = time.time() - start_time

    print(
        f"Epoch [{epoch+1}/{EYE_EPOCHS}] | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Acc: {train_accuracy*100:.2f}% | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_accuracy*100:.2f}% | "
        f"Time: {elapsed:.1f}s"
    )

    # Save best model
    if val_accuracy > best_eye_val_accuracy:

        best_eye_val_accuracy = val_accuracy

        torch.save(
            eye_model.state_dict(),
            "/content/eye_model.pth"
        )

        print("Best Eye Model saved!")

print("\nEye Model Training Complete!")
print(
    "Best Validation Accuracy:",
    f"{best_eye_val_accuracy*100:.2f}%"
)

# CELL 24 Load the best saved Eye Model
eye_model.load_state_dict(
    torch.load("/content/eye_model.pth", map_location=DEVICE)
)

# Evaluate on test dataset
test_loss, test_accuracy = validate_model(
    eye_model,
    eye_test_loader,
    criterion
)

print("✅ Eye Model Evaluation Complete!")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

#CELL 24
YAWN_EPOCHS = 5

best_yawn_val_accuracy = 0.0

yawn_history = {
    "train_loss": [],
    "train_accuracy": [],
    "val_loss": [],
    "val_accuracy": []
}

for epoch in range(YAWN_EPOCHS):

    start_time = time.time()

    # Training
    train_loss, train_accuracy = train_one_epoch(
        yawn_model,
        yawn_train_loader,
        yawn_optimizer,
        criterion
    )

    # Validation
    val_loss, val_accuracy = validate_model(
        yawn_model,
        yawn_val_loader,
        criterion
    )

    # Save history
    yawn_history["train_loss"].append(train_loss)
    yawn_history["train_accuracy"].append(train_accuracy)
    yawn_history["val_loss"].append(val_loss)
    yawn_history["val_accuracy"].append(val_accuracy)

    elapsed = time.time() - start_time

    print(
        f"Epoch [{epoch+1}/{YAWN_EPOCHS}] | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Acc: {train_accuracy*100:.2f}% | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Acc: {val_accuracy*100:.2f}% | "
        f"Time: {elapsed:.1f}s"
    )

    # Save best model
    if val_accuracy > best_yawn_val_accuracy:

        best_yawn_val_accuracy = val_accuracy

        torch.save(
            yawn_model.state_dict(),
            "/content/yawn_model.pth"
        )

        print("   ⭐ Best Yawn Model saved!")

print("\n✅ Yawn Model Training Complete!")
print(
    "Best Validation Accuracy:",
    f"{best_yawn_val_accuracy*100:.2f}%"
)

# CELL 25 Load the best saved Yawn Model
yawn_model.load_state_dict(
    torch.load("/content/yawn_model.pth", map_location=DEVICE)
)

# Evaluate on test dataset
test_loss, test_accuracy = validate_model(
    yawn_model,
    yawn_test_loader,
    criterion
)

print("✅ Yawn Model Evaluation Complete!")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

#CELL 26
import os
import shutil

# Create models folder
MODEL_DIR = "/content/drowsiness_models"
os.makedirs(MODEL_DIR, exist_ok=True)

# Save Eye Model
torch.save(
    eye_model.state_dict(),
    os.path.join(MODEL_DIR, "eye_model.pth")
)

# Save Yawn Model
torch.save(
    yawn_model.state_dict(),
    os.path.join(MODEL_DIR, "yawn_model.pth")
)

print("✅ Models saved successfully!")
print("\nSaved files:")

for file in os.listdir(MODEL_DIR):
    print("📁", file)

!pip install -q mediapipe

import os
import torch
import torch.nn as nn
from torchvision import models

# Check saved models
print("Checking saved models...")

print("Eye model exists:",
      os.path.exists("/content/drowsiness_models/eye_model.pth"))

print("Yawn model exists:",
      os.path.exists("/content/drowsiness_models/yawn_model.pth"))

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def create_drowsiness_model():
    model = models.resnet18(
        weights=None
    )
    model.fc = nn.Linear(model.fc.in_features, 2)
    return model.to(DEVICE)

# Create models
eye_model = create_drowsiness_model()
yawn_model = create_drowsiness_model()

# Load trained weights
eye_model.load_state_dict(
    torch.load(
        "/content/drowsiness_models/eye_model.pth",
        map_location=DEVICE
    )
)

yawn_model.load_state_dict(
    torch.load(
        "/content/drowsiness_models/yawn_model.pth",
        map_location=DEVICE
    )
)

# Evaluation mode
eye_model.eval()
yawn_model.eval()

print("✅ Eye model loaded!")
print("✅ Yawn model loaded!")
print("Using device:", DEVICE)

import cv2
import mediapipe as mp
import numpy as np

from torchvision import transforms
from PIL import Image

live_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

EYE_CLASSES = ["Closed_Eyes", "Open_Eyes"]
YAWN_CLASSES = ["No_yawn", "Yawn"]

print("MediaPipe version:", mp.__version__)
print("✅ Live detection setup complete!")
print("Eye classes:", EYE_CLASSES)
print("Yawn classes:", YAWN_CLASSES)

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np

def take_photo(quality=0.8):
    js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');

      const video = document.createElement('video');
      video.style.display = 'block';
      video.width = 640;
      video.height = 480;

      const button = document.createElement('button');
      button.textContent = '📸 Capture Photo';

      div.appendChild(video);
      div.appendChild(button);
      document.body.appendChild(div);

      const stream = await navigator.mediaDevices.getUserMedia({
        video: true
      });

      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => {
        button.onclick = resolve;
      });

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;

      canvas.getContext('2d').drawImage(
        video, 0, 0
      );

      stream.getVideoTracks()[0].stop();
      div.remove();

      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')

    display(js)

    data = eval_js('takePhoto(%f)' % quality)

    binary = b64decode(data.split(',')[1])

    image = np.frombuffer(binary, dtype=np.uint8)

    frame = cv2.imdecode(image, cv2.IMREAD_COLOR)

    return frame


print("📷 Click the camera button when it appears.")

frame = take_photo()

print("✅ Camera working!")
print("Frame shape:", frame.shape)

# Convert BGR → RGB for correct display
frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

display(frame_rgb)

import os
import urllib.request

MODEL_PATH = "/content/face_landmarker.task"

MODEL_URL = "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task"

if not os.path.exists(MODEL_PATH):
    urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)

print("✅ Face Landmarker model ready!")
print("File exists:", os.path.exists(MODEL_PATH))

import mediapipe as mp

from mediapipe.tasks import python
from mediapipe.tasks.python import vision

base_options = python.BaseOptions(
    model_asset_path="/content/face_landmarker.task"
)

options = vision.FaceLandmarkerOptions(
    base_options=base_options,
    output_face_blendshapes=False,
    output_facial_transformation_matrixes=False,
    num_faces=1
)

face_landmarker = vision.FaceLandmarker.create_from_options(options)

print("✅ MediaPipe Face Landmarker ready!")

import cv2
import numpy as np
import matplotlib.pyplot as plt
import mediapipe as mp

# Convert BGR to RGB
rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

# Convert to MediaPipe Image
mp_image = mp.Image(
    image_format=mp.ImageFormat.SRGB,
    data=rgb_frame
)

# Detect face landmarks
result = face_landmarker.detect(mp_image)

if len(result.face_landmarks) > 0:

    print("✅ Face landmarks detected!")

    landmarks = result.face_landmarks[0]

    output = rgb_frame.copy()
    h, w, _ = output.shape

    # Draw landmarks
    for landmark in landmarks:
        x = int(landmark.x * w)
        y = int(landmark.y * h)

        if 0 <= x < w and 0 <= y < h:
            cv2.circle(
                output,
                (x, y),
                1,
                (0, 255, 0),
                -1
            )

    plt.figure(figsize=(10, 7))
    plt.imshow(output)
    plt.axis("off")
    plt.show()

    print("Number of face landmarks:", len(landmarks))

else:
    print("❌ No face landmarks detected.")

# Face landmark points used for eye and mouth regions

h, w, _ = frame.shape

# Landmark indexes
LEFT_EYE = [33, 133, 159, 145, 160, 144]
RIGHT_EYE = [362, 263, 386, 374, 387, 373]

# Mouth landmarks
MOUTH = [
    61, 291, 0, 17,
    269, 405, 306, 375,
    78, 308, 13, 14
]

def get_region(image, landmarks, indices, padding=10):

    h, w, _ = image.shape

    points = []

    for index in indices:
        landmark = landmarks[index]

        x = int(landmark.x * w)
        y = int(landmark.y * h)

        points.append((x, y))

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]

    x1 = max(0, min(xs) - padding)
    y1 = max(0, min(ys) - padding)
    x2 = min(w, max(xs) + padding)
    y2 = min(h, max(ys) + padding)

    return image[y1:y2, x1:x2]


# Extract regions from original RGB frame
left_eye = get_region(
    rgb_frame,
    landmarks,
    LEFT_EYE,
    padding=15
)

right_eye = get_region(
    rgb_frame,
    landmarks,
    RIGHT_EYE,
    padding=15
)

mouth = get_region(
    rgb_frame,
    landmarks,
    MOUTH,
    padding=20
)

# Display extracted regions
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(left_eye)
plt.title("Left Eye")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(right_eye)
plt.title("Right Eye")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(mouth)
plt.title("Mouth")
plt.axis("off")

plt.show()

print("✅ Eye and mouth regions extracted!")

# Function to predict using a trained model
def predict_region(model, image, class_names):

    # Convert NumPy image to PIL
    pil_image = Image.fromarray(image)

    # Preprocess
    input_tensor = live_transform(pil_image)

    # Add batch dimension
    input_tensor = input_tensor.unsqueeze(0).to(DEVICE)

    # Prediction
    with torch.no_grad():
        output = model(input_tensor)
        probabilities = torch.softmax(output, dim=1)

        predicted_index = torch.argmax(probabilities, dim=1).item()
        confidence = probabilities[0][predicted_index].item()

    predicted_class = class_names[predicted_index]

    return predicted_class, confidence


# Predict left eye
left_eye_prediction, left_eye_confidence = predict_region(
    eye_model,
    left_eye,
    EYE_CLASSES
)

# Predict right eye
right_eye_prediction, right_eye_confidence = predict_region(
    eye_model,
    right_eye,
    EYE_CLASSES
)

# Predict mouth
mouth_prediction, mouth_confidence = predict_region(
    yawn_model,
    mouth,
    YAWN_CLASSES
)


print("========== DROWSINESS PREDICTION ==========")

print(
    f"Left Eye  : {left_eye_prediction} "
    f"({left_eye_confidence*100:.2f}%)"
)

print(
    f"Right Eye : {right_eye_prediction} "
    f"({right_eye_confidence*100:.2f}%)"
)

print(
    f"Mouth     : {mouth_prediction} "
    f"({mouth_confidence*100:.2f}%)"
)

# ==========================================
# FINAL DROWSINESS DECISION
# ==========================================

both_eyes_closed = (
    left_eye_prediction == "Closed_Eyes"
    and
    right_eye_prediction == "Closed_Eyes"
)

is_yawning = (
    mouth_prediction == "Yawn"
)

# Final decision
if both_eyes_closed or is_yawning:
    drowsiness_status = "DROWSY"
else:
    drowsiness_status = "ALERT"

print("================================")
print("      DROWSINESS STATUS")
print("================================")

print("Left Eye  :", left_eye_prediction)
print("Right Eye :", right_eye_prediction)
print("Mouth     :", mouth_prediction)

print("--------------------------------")

if drowsiness_status == "DROWSY":
    print("🚨 STATUS: DROWSY")
    print("⚠️ WARNING: Please take a break!")
else:
    print("✅ STATUS: ALERT")
    print("👍 Driver appears to be awake.")

print("================================")

from IPython.display import Audio, display
import numpy as np

# Create a short warning tone
sample_rate = 44100
duration = 1.0

t = np.linspace(
    0,
    duration,
    int(sample_rate * duration),
    False
)

# Warning beep
tone = 0.5 * np.sin(2 * np.pi * 1000 * t)

print("🔊 Testing drowsiness alarm...")

display(
    Audio(
        tone,
        rate=sample_rate,
        autoplay=True
    )
)

print("✅ Alarm test complete!")

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np
import matplotlib.pyplot as plt
import time

# --------------------------------------------------
# Camera capture function
# --------------------------------------------------

def capture_frame():
    js = Javascript('''
    async function captureFrame() {

        const video = document.createElement('video');

        video.style.display = 'block';
        video.width = 640;
        video.height = 480;

        const stream =
            await navigator.mediaDevices.getUserMedia({
                video: true
            });

        video.srcObject = stream;

        await video.play();

        // Wait briefly for camera frame
        await new Promise(resolve =>
            setTimeout(resolve, 500)
        );

        const canvas =
            document.createElement('canvas');

        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;

        canvas.getContext('2d')
            .drawImage(
                video,
                0,
                0
            );

        stream.getVideoTracks()[0].stop();

        return canvas.toDataURL(
            'image/jpeg',
            0.8
        );
    }
    ''')

    display(js)

    data = eval_js('captureFrame()')

    binary = b64decode(
        data.split(',')[1]
    )

    image = np.frombuffer(
        binary,
        dtype=np.uint8
    )

    frame = cv2.imdecode(
        image,
        cv2.IMREAD_COLOR
    )

    return frame


# --------------------------------------------------
# Drowsiness prediction
# --------------------------------------------------

def predict_drowsiness(frame):

    rgb_frame = cv2.cvtColor(
        frame,
        cv2.COLOR_BGR2RGB
    )

    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb_frame
    )

    result = face_landmarker.detect(
        mp_image
    )

    if len(result.face_landmarks) == 0:
        return frame, "NO FACE"

    landmarks = result.face_landmarks[0]

    # -----------------------------
    # Landmark indexes
    # -----------------------------

    LEFT_EYE = [
        33, 133, 159,
        145, 160, 144
    ]

    RIGHT_EYE = [
        362, 263, 386,
        374, 387, 373
    ]

    MOUTH = [
        61, 291, 0, 17,
        269, 405, 306, 375,
        78, 308, 13, 14
    ]

    # -----------------------------
    # Extract region
    # -----------------------------

    def get_region(
        image,
        landmarks,
        indices,
        padding
    ):

        h, w, _ = image.shape

        points = []

        for index in indices:

            landmark = landmarks[index]

            x = int(
                landmark.x * w
            )

            y = int(
                landmark.y * h
            )

            points.append(
                (x, y)
            )

        xs = [p[0] for p in points]
        ys = [p[1] for p in points]

        x1 = max(
            0,
            min(xs) - padding
        )

        y1 = max(
            0,
            min(ys) - padding
        )

        x2 = min(
            w,
            max(xs) + padding
        )

        y2 = min(
            h,
            max(ys) + padding
        )

        return image[
            y1:y2,
            x1:x2
        ]

    # Extract regions
    left_eye = get_region(
        rgb_frame,
        landmarks,
        LEFT_EYE,
        15
    )

    right_eye = get_region(
        rgb_frame,
        landmarks,
        RIGHT_EYE,
        15
    )

    mouth = get_region(
        rgb_frame,
        landmarks,
        MOUTH,
        20
    )

    # -----------------------------
    # Prediction
    # -----------------------------

    left_eye_prediction, _ = predict_region(
        eye_model,
        left_eye,
        EYE_CLASSES
    )

    right_eye_prediction, _ = predict_region(
        eye_model,
        right_eye,
        EYE_CLASSES
    )

    mouth_prediction, _ = predict_region(
        yawn_model,
        mouth,
        YAWN_CLASSES
    )

    # -----------------------------
    # Decision
    # -----------------------------

    both_eyes_closed = (
        left_eye_prediction == "Closed_Eyes"
        and
        right_eye_prediction == "Closed_Eyes"
    )

    is_yawning = (
        mouth_prediction == "Yawn"
    )

    if both_eyes_closed or is_yawning:

        status = "DROWSY"

    else:

        status = "ALERT"

    # -----------------------------
    # Display status
    # -----------------------------

    output = frame.copy()

    if status == "DROWSY":

        text = "DROWSY - WARNING!"

    else:

        text = "ALERT - AWAKE"

    cv2.putText(
        output,
        text,
        (30, 50),
        cv2.FONT_HERSHEY_SIMPLEX,
        1.2,
        (0, 0, 255)
        if status == "DROWSY"
        else (0, 255, 0),
        3
    )

    cv2.putText(
        output,
        "Left Eye: " +
        left_eye_prediction,
        (30, 90),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (255, 255, 255),
        2
    )

    cv2.putText(
        output,
        "Right Eye: " +
        right_eye_prediction,
        (30, 120),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (255, 255, 255),
        2
    )

    cv2.putText(
        output,
        "Mouth: " +
        mouth_prediction,
        (30, 150),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (255, 255, 255),
        2
    )

    return output, status


# --------------------------------------------------
# Run live detection
# --------------------------------------------------

print("📷 Starting live drowsiness detection...")

for i in range(10):

    frame = capture_frame()

    output, status = predict_drowsiness(
        frame
    )

    output_rgb = cv2.cvtColor(
        output,
        cv2.COLOR_BGR2RGB
    )

    display(
        output_rgb
    )

    print(
        f"Frame {i+1}/10 → {status}"
    )

    time.sleep(0.5)

print("✅ Live detection test complete!")

# ==========================================
# CELL 35 — STABLE DROWSINESS DECISION
# ==========================================

DROWSY_FRAME_LIMIT = 3
drowsy_counter = 0

print("✅ Stable drowsiness logic ready!")

for i in range(10):

    frame = capture_frame()

    output, status = predict_drowsiness(frame)

    # Count consecutive DROWSY frames
    if status == "DROWSY":
        drowsy_counter += 1
    else:
        drowsy_counter = 0

    # Final stable decision
    if drowsy_counter >= DROWSY_FRAME_LIMIT:

        final_status = "DROWSY"

        print(
            f"🚨 WARNING! Drowsiness detected "
            f"for {drowsy_counter} consecutive frames."
        )

    else:

        final_status = "ALERT"

    # Add final status to image
    if final_status == "DROWSY":

        cv2.putText(
            output,
            "🚨 DROWSINESS ALERT!",
            (30, 200),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.9,
            (0, 0, 255),
            3
        )

    else:

        cv2.putText(
            output,
            "STATUS: ALERT",
            (30, 200),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.9,
            (0, 255, 0),
            3
        )

    output_rgb = cv2.cvtColor(
        output,
        cv2.COLOR_BGR2RGB
    )

    display(output_rgb)

    print(
        f"Frame {i+1}/10 | "
        f"Model: {status} | "
        f"Final: {final_status} | "
        f"Drowsy count: {drowsy_counter}"
    )

    time.sleep(0.5)

print("\n✅ Stable drowsiness test complete!")

import os

print("Eye model:", os.path.exists("/content/drowsiness_models/eye_model.pth"))
print("Yawn model:", os.path.exists("/content/drowsiness_models/yawn_model.pth"))

from torch.utils.data import Dataset, DataLoader
from torchvision.datasets import ImageFolder
from torchvision import transforms

# ==========================================
# BINARY DATASET CLASS
# ==========================================

class BinaryDrowsinessDataset(Dataset):

    def __init__(self, image_folder_dataset, selected_classes):

        self.dataset = image_folder_dataset
        self.selected_classes = selected_classes

        self.class_to_idx = {
            class_name: index
            for index, class_name in enumerate(selected_classes)
        }

        self.selected_indices = []

        for index, (_, label) in enumerate(self.dataset.samples):

            original_class = self.dataset.classes[label]

            if original_class in selected_classes:
                self.selected_indices.append(index)

    def __len__(self):
        return len(self.selected_indices)

    def __getitem__(self, index):

        original_index = self.selected_indices[index]

        image, original_label = self.dataset[original_index]

        original_class = self.dataset.classes[original_label]

        new_label = self.class_to_idx[original_class]

        return image, new_label


print("✅ BinaryDrowsinessDataset recreated!")

# ==========================================
# RECREATE TEST DATALOADERS
# ==========================================

IMAGE_SIZE = 224

val_test_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

TEST_DIR = "/content/drowsiness_dataset/Dataset/Test"

test_full = ImageFolder(
    TEST_DIR,
    transform=val_test_transform
)

eye_classes = ["Closed_Eyes", "Open_Eyes"]
yawn_classes = ["No_yawn", "Yawn"]

eye_test = BinaryDrowsinessDataset(
    test_full,
    eye_classes
)

yawn_test = BinaryDrowsinessDataset(
    test_full,
    yawn_classes
)

eye_test_loader = DataLoader(
    eye_test,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

yawn_test_loader = DataLoader(
    yawn_test,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

print("✅ Test DataLoaders recreated!")
print("Eye test images:", len(eye_test))
print("Yawn test images:", len(yawn_test))

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt
import numpy as np
import torch


# ==========================================
# FUNCTION FOR DETAILED EVALUATION
# ==========================================

def detailed_evaluation(model, loader, class_names, model_name):

    model.eval()

    all_predictions = []
    all_labels = []

    with torch.no_grad():

        for images, labels in loader:

            images = images.to(DEVICE)

            outputs = model(images)

            predictions = torch.argmax(
                outputs,
                dim=1
            )

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_labels.extend(
                labels.numpy()
            )

    # Metrics
    accuracy = accuracy_score(
        all_labels,
        all_predictions
    )

    precision = precision_score(
        all_labels,
        all_predictions,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        all_labels,
        all_predictions,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        all_labels,
        all_predictions,
        average="weighted",
        zero_division=0
    )

    # Print results
    print("\n====================================")
    print(model_name)
    print("====================================")

    print(f"Accuracy  : {accuracy * 100:.2f}%")
    print(f"Precision : {precision * 100:.2f}%")
    print(f"Recall    : {recall * 100:.2f}%")
    print(f"F1-Score  : {f1 * 100:.2f}%")

    # Confusion Matrix
    cm = confusion_matrix(
        all_labels,
        all_predictions
    )

    print("\nConfusion Matrix:")
    print(cm)

    # Display confusion matrix
    display = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=class_names
    )

    fig, ax = plt.subplots(
        figsize=(6, 6)
    )

    display.plot(
        ax=ax,
        values_format="d"
    )

    plt.title(
        model_name + " - Confusion Matrix"
    )

    plt.show()

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "confusion_matrix": cm
    }


# ==========================================
# EYE MODEL
# ==========================================

eye_results = detailed_evaluation(
    eye_model,
    eye_test_loader,
    EYE_CLASSES,
    "Eye Model"
)


# ==========================================
# YAWN MODEL
# ==========================================

yawn_results = detailed_evaluation(
    yawn_model,
    yawn_test_loader,
    YAWN_CLASSES,
    "Yawn Model"
)

print("\n✅ Detailed evaluation completed!")
